"""Add imagem column to Aves

Revision ID: fcc4429ec0a4
Revises: 
Create Date: 2025-04-05 20:41:10.401693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc4429ec0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especies')
    with op.batch_alter_table('aves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=99),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aves', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=99),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('imagem')

    op.create_table('especies',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('especie', sa.TEXT(), nullable=False),
    sa.Column('nome_comum', sa.TEXT(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=False),
    sa.Column('imagem', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
